import React, { createContext, useEffect, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      skills: 'Skills',
      projects: 'Projects',
      internships: 'Experience',
      certificates: 'Certificates',
      viewCV: 'View CV',
      contact: 'Contact',
      backToTop: 'Back to top'
    },
    home: {
      greeting: "Hello, my name is",
      name: "Youssef Fawel",
      tagline: "And I'm a",
      description: "Software Engineer building reliable full-stack products and AI-assisted experiences. I turn complex requirements into secure, accessible and maintainable web and mobile applications.",
      hireMeBtn: "Get In Touch",
      portfolioBtn: "View Portfolio",
      downloadCVBtn: "Download CV",
      learnMore: "Learn More About Me",
      viewAllSkills: "View All Skills",
      viewAllProjects: "View All Projects",
      viewAllInternships: "View All Internships",
      viewAllCertificates: "View All Certificates",
      viewFullCV: "View Full CV",
      titles: [
        "Software Engineer",
        "Full-Stack Engineer",
        "AI-Integrated App Developer",
        "Web & Mobile Developer"
      ]
    },
    about: {
      title: "About Me",
      subtitle: "Who I am",
      heading: "I'm Youssef, a",
      description1: "I am a Software Engineer and engineering graduate in Computer Science / Software Engineering from EPI Digital School. I graduated with the distinction “Excellent” and focus on full-stack systems, modern web applications and practical AI integrations.",
      description2: "My academic journey also included an exchange experience at ESIEA — École d'ingénieur·e·s d'un numérique utile in Paris. Combined with my professional experience in France and Tunisia, it strengthened my ability to work across cultures and deliver clear, dependable software.",
      downloadCV: "Download CV",
      viewWork: "View My Work",
      name: "Name",
      email: "Email",
      esieaEmail: "ESIEA Email",
      degree: "Degree",
      degreeValue: "Engineering degree in Computer Science",
      location: "Location",
      locationValue: "Paris, France",
      study: "Study",
      studyValue: "EPI Digital School · ESIEA exchange",
      graduation: "Graduated",
      graduationValue: "2026",
      distinction: "Distinction",
      distinctionValue: "Excellent"
    },
    skills: {
      title: "My Skills",
      subtitle: "Expertise and proficiencies I've developed over the years",
      description: "A practical full-stack toolkit shaped by production work, engineering projects and continuous learning across web, mobile, data and AI-assisted systems.",
      technicalSkills: "Technical Skills",
      softSkills: "Soft Skills",
      toolsTech: "Tools & Technologies",
      myExpertise: "My Expertise",
      expertiseDesc1: "I build end-to-end applications with typed frontends, API-driven backends and relational data models, with particular attention to security, maintainability and user experience.",
      expertiseDesc2: "My recent work spans Next.js, Angular, NestJS, FastAPI, PostgreSQL, Flutter and Gemini integrations, supported by testing, deployment and collaborative delivery practices.",
      viewProjects: "View My Projects",
      getInTouch: "Get In Touch",
      beginner: "Beginner (0-69%)",
      intermediate: "Intermediate (70-84%)",
      advanced: "Advanced (85-100%)",
      frontend: "Frontend",
      backend: "Backend",
      mobile: "Mobile Development",
      database: "Database",
      communication: "Communication",
      writtenCommunication: "Written Communication",
      verbalCommunication: "Verbal Communication",
      presentation: "Presentation",
      documentation: "Documentation",
      collaboration: "Collaboration",
      teamwork: "Teamwork",
      leadership: "Leadership",
      conflictResolution: "Conflict Resolution",
      mentoring: "Mentoring",
      problemSolving: "Problem Solving",
      criticalThinking: "Critical Thinking",
      analyticalSkills: "Analytical Skills",
      creativity: "Creativity",
      attentionToDetail: "Attention to Detail",
      devTools: "Development Tools",
      gitGithub: "Git & GitHub",
      postman: "Postman",
      vsCode: "VS Code",
      androidStudio: "Android Studio",
      webpack: "Webpack",
      npmYarn: "npm/yarn",
      designTools: "Design Tools",
      figma: "Figma",
      adobeXd: "Adobe XD",
      photoshop: "Photoshop",
      illustrator: "Illustrator",
      projectManagement: "Project Management",
      jira: "Jira",
      trello: "Trello",
      agileScrum: "Agile/Scrum"
    },
    projects: {
      title: "My Projects",
      subtitle: "A collection of my work and personal projects",
      all: "All",
      web: "Web",
      mobile: "Mobile",
      html: "HTML",
      javascript: "JavaScript",
      react: "React",
      fullstack: "Full Stack",
      featured: "Featured",
      learnMore: "Learn More",
      liveDemo: "Live Demo",
      viewCode: "View Code",
      linkedinPost: "LinkedIn Post",
      noProjects: "No projects found",
      noProjectsDesc: "There are no projects in this category yet.",
      viewAllProjects: "View All Projects",
      projectOverview: "Project Overview",
      keyFeatures: "Key Features",
      client: "Client",
      date: "Date",
      duration: "Duration",
      myRole: "My Role",
      technologiesUsed: "Technologies Used",
      challengesSolutions: "Challenges & Solutions",
      close: "Close",
      allFilter: "All",
      searchPlaceholder: "Search projects..."
    },
    internships: {
      title: "Experience",
      subtitle: "Professional experience and engineering internships",
      duration: "Duration",
      location: "Location",
      skills: "Skills",
      months: "mos",
      month: "mo",
      remote: "Remote",
      onsite: "On-site",
      hybrid: "Hybrid"
    },
    certificates: {
      title: "My Certificates",
      subtitle: "A collection of my professional certifications and achievements",
      searchPlaceholder: "Search certificates...",
      loading: "Loading certificates...",
      showing: "Showing",
      of: "of",
      certificatesIn: "certificates in"
    },
    viewCV: {
      title: "My Curriculum Vitae",
      subtitle: "Get to know my professional journey and qualifications",
      professionalSummary: "Professional Summary",
      summaryText1: "I am a Software Engineer specializing in full-stack product development, secure APIs and AI-assisted workflows. My experience covers modern web and mobile interfaces, backend services, relational databases and production deployment.",
      summaryText2: "My CV presents my professional experience, engineering degree, technical skills and recent projects, including Talentry, AHKILI and SABA.",
      whatsInside: "What's Inside",
      experience: "Professional Experience",
      experienceDesc: "Detailed work history with key achievements and responsibilities.",
      technicalSkills: "Technical Skills",
      technicalSkillsDesc: "Comprehensive list of programming languages, frameworks, and tools.",
      education: "Education & Certifications",
      educationDesc: "Academic background and professional certifications.",
      projects: "Projects",
      projectsDesc: "Showcase of significant projects with technologies used and outcomes.",
      downloadCV: "Download CV",
      previewCV: "Preview CV",
      viewFull: "View Full CV",
      educationLabel: "Education",
      educationValue: "Engineering degree · Mention Excellent",
      languagesLabel: "Languages",
      languagesValue: "Arabic, French, English",
      phoneLabel: "Phone",
      connect: "Connect with me",
      profileTitle: "Software Engineer · Full-Stack",
      previewTitle: "CV preview",
      download: "Download",
      close: "Close"
    },
    contact: {
      title: "Contact Me",
      subtitle: "Get in Touch",
      name: "Name",
      namePlaceholder: "Your name",
      email: "Email",
      emailPlaceholder: "Your email",
      subject: "Subject",
      message: "Message",
      messagePlaceholder: "Write your message here...",
      sendBtn: "Send Message",
      getInTouch: "Get in Touch",
      sendMessage: "Send Me a Message",
      description: "I'm always open to new opportunities and collaborations. Feel free to reach out to me using the form or through my contact information below.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      locationLabel: "Location",
      nameRequired: "Name is required",
      emailRequired: "Email is required",
      emailInvalid: "Email address is invalid",
      messageRequired: "Message is required",
      messageShort: "Message must be at least 10 characters",
      responseTime: "I'll get back to you as soon as possible.",
      sending: "Sending your message...",
      sendError: "Something went wrong. Please try again later."
    },
    linkedin: {
      title: "LinkedIn",
      author: "Youssef Fawel",
      subtitle: "Software Engineer",
      content1: "Software Engineer · Full-Stack development · AI-integrated applications",
      content2: "Discover my professional experience and the engineering behind Talentry, AHKILI and SABA on my LinkedIn profile.",
      visitBtn: "Visit My LinkedIn Profile",
      closeBtn: "Close",
      countdown: "LinkedIn in:"
    },
    footer: {
      createdBy: "Developed and Designed by",
      rights: "All rights reserved."
    }
  },
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      skills: 'Compétences',
      projects: 'Projets',
      internships: 'Expérience',
      certificates: 'Certificats',
      viewCV: 'Voir CV',
      contact: 'Contact',
      backToTop: 'Retour en haut'
    },
    home: {
      greeting: "Bonjour, je m'appelle",
      name: "Youssef Fawel",
      tagline: "Et je suis",
      description: "Ingénieur en informatique, je conçois des produits Full-stack fiables et des expériences assistées par IA. Je transforme des besoins complexes en applications web et mobiles sécurisées, accessibles et maintenables.",
      hireMeBtn: "Prenez Contact",
      portfolioBtn: "Voir le Portfolio",
      downloadCVBtn: "Télécharger CV",
      learnMore: "En Savoir Plus Sur Moi",
      viewAllSkills: "Voir Toutes les Compétences",
      viewAllProjects: "Voir Tous les Projets",
      viewAllInternships: "Voir Tous les Stages",
      viewAllCertificates: "Voir Tous les Certificats",
      viewFullCV: "Voir le CV Complet",
      titles: [
        "Ingénieur en informatique",
        "Ingénieur Full-stack",
        "Développeur d'applications avec IA",
        "Développeur Web & Mobile"
      ]
    },
    about: {
      title: "À Propos de Moi",
      subtitle: "Qui je suis",
      heading: "Je suis Youssef,",
      description1: "Je suis ingénieur en informatique, diplômé de l'EPI Digital School avec la mention « Excellent ». Je me spécialise dans les systèmes Full-stack, les applications web modernes et les intégrations d'intelligence artificielle utiles.",
      description2: "Mon parcours comprend également une expérience d'échange à l'ESIEA — École d'ingénieur·e·s d'un numérique utile à Paris. Associée à mes expériences professionnelles en France et en Tunisie, elle a renforcé ma capacité à collaborer dans des contextes internationaux et à livrer des logiciels fiables.",
      downloadCV: "Télécharger CV",
      viewWork: "Voir Mon Travail",
      name: "Nom",
      email: "Email",
      esieaEmail: "Email ESIEA",
      degree: "Diplôme",
      degreeValue: "Diplôme d'ingénieur en informatique",
      location: "Lieu",
      locationValue: "Paris, France",
      study: "Études",
      studyValue: "EPI Digital School · échange ESIEA",
      graduation: "Diplômé en",
      graduationValue: "2026",
      distinction: "Mention",
      distinctionValue: "Excellent"
    },
    skills: {
      title: "Mes Compétences",
      subtitle: "Expertise et compétences que j'ai développées au fil des années",
      description: "Une boîte à outils Full-stack concrète, développée en production, lors de projets d'ingénierie et par une veille continue autour du web, du mobile, des données et de l'IA.",
      technicalSkills: "Compétences Techniques",
      softSkills: "Compétences Relationnelles",
      toolsTech: "Outils et Technologies",
      myExpertise: "Mon Expertise",
      expertiseDesc1: "Je développe des applications de bout en bout avec des interfaces typées, des API robustes et des modèles de données relationnels, en privilégiant la sécurité, la maintenabilité et l'expérience utilisateur.",
      expertiseDesc2: "Mes travaux récents couvrent Next.js, Angular, NestJS, FastAPI, PostgreSQL, Flutter et les intégrations Gemini, avec des pratiques de test, de déploiement et de livraison collaborative.",
      viewProjects: "Voir Mes Projets",
      getInTouch: "Prenez Contact",
      beginner: "Débutant (0-69%)",
      intermediate: "Intermédiaire (70-84%)",
      advanced: "Avancé (85-100%)",
      frontend: "Frontend",
      backend: "Backend",
      mobile: "Développement Mobile",
      database: "Base de Données",
      communication: "Communication",
      writtenCommunication: "Communication Écrite",
      verbalCommunication: "Communication Verbale",
      presentation: "Présentation",
      documentation: "Documentation",
      collaboration: "Collaboration",
      teamwork: "Travail d'Équipe",
      leadership: "Leadership",
      conflictResolution: "Résolution de Conflits",
      mentoring: "Mentorat",
      problemSolving: "Résolution de Problèmes",
      criticalThinking: "Pensée Critique",
      analyticalSkills: "Compétences Analytiques",
      creativity: "Créativité",
      attentionToDetail: "Souci du Détail",
      devTools: "Outils de Développement",
      gitGithub: "Git & GitHub",
      postman: "Postman",
      vsCode: "VS Code",
      androidStudio: "Android Studio",
      webpack: "Webpack",
      npmYarn: "npm/yarn",
      designTools: "Outils de Design",
      figma: "Figma",
      adobeXd: "Adobe XD",
      photoshop: "Photoshop",
      illustrator: "Illustrator",
      projectManagement: "Gestion de Projet",
      jira: "Jira",
      trello: "Trello",
      agileScrum: "Agile/Scrum"
    },
    projects: {
      title: "Mes Projets",
      subtitle: "Une collection de mes travaux et projets personnels",
      all: "Tous",
      web: "Web",
      mobile: "Mobile",
      html: "HTML",
      javascript: "JavaScript",
      react: "React",
      fullstack: "Full Stack",
      featured: "En Vedette",
      learnMore: "En Savoir Plus",
      liveDemo: "Démo en Direct",
      viewCode: "Voir le Code",
      linkedinPost: "Publication LinkedIn",
      noProjects: "Aucun projet trouvé",
      noProjectsDesc: "Il n'y a pas encore de projets dans cette catégorie.",
      viewAllProjects: "Voir Tous les Projets",
      projectOverview: "Aperçu du Projet",
      keyFeatures: "Caractéristiques Principales",
      client: "Client",
      date: "Date",
      duration: "Durée",
      myRole: "Mon Rôle",
      technologiesUsed: "Technologies Utilisées",
      challengesSolutions: "Défis et Solutions",
      close: "Fermer",
      allFilter: "Tous",
      searchPlaceholder: "Rechercher des projets..."
    },
    internships: {
      title: "Expérience",
      subtitle: "Expériences professionnelles et stages d'ingénierie",
      duration: "Durée",
      location: "Lieu",
      skills: "Compétences",
      months: "mois",
      month: "mois",
      remote: "À distance",
      onsite: "Sur site",
      hybrid: "Hybride"
    },
    certificates: {
      title: "Mes Certificats",
      subtitle: "Une collection de mes certifications professionnelles et réalisations",
      searchPlaceholder: "Rechercher des certificats...",
      loading: "Chargement des certificats...",
      showing: "Affichage de",
      of: "sur",
      certificatesIn: "certificats dans"
    },
    viewCV: {
      title: "Mon Curriculum Vitae",
      subtitle: "Découvrez mon parcours professionnel et mes qualifications",
      professionalSummary: "Résumé Professionnel",
      summaryText1: "Je suis ingénieur en informatique, spécialisé dans le développement de produits Full-stack, les API sécurisées et les parcours assistés par IA. Mon expérience couvre les interfaces web et mobiles, les services backend, les bases relationnelles et le déploiement en production.",
      summaryText2: "Mon CV présente mon expérience professionnelle, mon diplôme d'ingénieur, mes compétences techniques et mes projets récents, notamment Talentry, AHKILI et SABA.",
      whatsInside: "Contenu",
      experience: "Expérience Professionnelle",
      experienceDesc: "Historique de travail détaillé avec les réalisations et responsabilités clés.",
      technicalSkills: "Compétences Techniques",
      technicalSkillsDesc: "Liste complète des langages de programmation, frameworks et outils.",
      education: "Formation et Certifications",
      educationDesc: "Parcours académique et certifications professionnelles.",
      projects: "Projets",
      projectsDesc: "Présentation de projets significatifs avec les technologies utilisées et les résultats.",
      downloadCV: "Télécharger CV",
      previewCV: "Prévisualiser CV",
      viewFull: "Voir le CV Complet",
      educationLabel: "Formation",
      educationValue: "Diplôme d'ingénieur · Mention Excellent",
      languagesLabel: "Langues",
      languagesValue: "Arabe, français, anglais",
      phoneLabel: "Téléphone",
      connect: "Me retrouver en ligne",
      profileTitle: "Ingénieur en informatique · Full-stack",
      previewTitle: "Aperçu du CV",
      download: "Télécharger",
      close: "Fermer"
    },
    contact: {
      title: "Contactez-moi",
      subtitle: "Prenez Contact",
      name: "Nom",
      namePlaceholder: "Votre nom",
      email: "Email",
      emailPlaceholder: "Votre email",
      subject: "Sujet",
      message: "Message",
      messagePlaceholder: "Écrivez votre message ici...",
      sendBtn: "Envoyer le Message",
      getInTouch: "Prenez Contact",
      sendMessage: "Envoyez-moi un Message",
      description: "Je suis toujours ouvert aux nouvelles opportunités et collaborations. N'hésitez pas à me contacter via le formulaire ou mes coordonnées ci-dessous.",
      emailLabel: "Email",
      phoneLabel: "Téléphone",
      locationLabel: "Localisation",
      nameRequired: "Le nom est requis",
      emailRequired: "L'email est requis",
      emailInvalid: "L'adresse email est invalide",
      messageRequired: "Le message est requis",
      messageShort: "Le message doit contenir au moins 10 caractères",
      responseTime: "Je vous répondrai dans les meilleurs délais.",
      sending: "Envoi de votre message...",
      sendError: "Une erreur est survenue. Veuillez réessayer plus tard."
    },
    linkedin: {
      title: "LinkedIn",
      author: "Youssef Fawel",
      subtitle: "Ingénieur en informatique",
      content1: "Ingénieur en informatique · Développement Full-stack · Applications intégrant l'IA",
      content2: "Découvrez mon expérience professionnelle ainsi que l'ingénierie de Talentry, AHKILI et SABA sur mon profil LinkedIn.",
      visitBtn: "Visiter Mon Profil LinkedIn",
      closeBtn: "Fermer",
      countdown: "LinkedIn dans :"
    },
    footer: {
      createdBy: "Développé et Conçu par",
      rights: "Tous droits réservés."
    }
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return window.localStorage.getItem('portfolio-language') === 'fr' ? 'fr' : 'en';
  });

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem('portfolio-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'fr' : 'en');
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
