[build]
  command = "npm run build"
  publish = "dist"  # or "build" if you're using Create React App

# Handle form submissions properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
